import "server-only";import{adminDb}from"@/lib/licensing/admin-db";import type{SmsRecord}from"./types";
function db(){if(!adminDb)throw new Error("SMS storage is unavailable. Configure Firebase Admin credentials.");return adminDb}
export async function claimSmsRequest(userId:string,requestId:string,limit:number){const d=db(),requestRef=d.collection("sms_requests").doc(`${userId}_${requestId}`),bucket=Math.floor(Date.now()/60000),rateRef=d.collection("sms_rate_limits").doc(`${userId}_${bucket}`);return d.runTransaction(async tx=>{const[existing,rate]=await Promise.all([tx.get(requestRef),tx.get(rateRef)]);if(existing.exists)return{claimed:false,recordId:String(existing.data()?.recordId??"")};const count=Number(rate.data()?.count??0);if(count>=limit)throw new Error("SMS_RATE_LIMIT");const recordId=d.collection("sms_messages").doc().id;tx.set(requestRef,{userId,requestId,recordId,createdAt:new Date().toISOString()});tx.set(rateRef,{userId,bucket,count:count+1,expiresAt:new Date(Date.now()+120000).toISOString()},{merge:true});return{claimed:true,recordId}})}
export async function saveSms(record:SmsRecord){await db().collection("sms_messages").doc(record.id).set(record)}
export async function updateSmsByProviderId(providerMessageId:string,data:Partial<SmsRecord>){const snap=await db().collection("sms_messages").where("providerMessageId","==",providerMessageId).limit(1).get();if(!snap.empty)await snap.docs[0].ref.set({...data,updatedAt:new Date().toISOString()},{merge:true})}
export async function listUserSms(userId:string,limit=50){const snap=await db().collection("sms_messages").where("userId","==",userId).orderBy("createdAt","desc").limit(Math.min(limit,100)).get();return snap.docs.map(d=>d.data()as SmsRecord)}
export async function getSms(id:string,userId:string){const s=await db().collection("sms_messages").doc(id).get();return s.exists&&s.data()?.userId===userId?s.data()as SmsRecord:null}
export async function isSmsSuspended(userId:string){return(await db().collection("sms_settings").doc(userId).get()).data()?.suspended===true}
export async function adminSmsSummary(){const[messages,settings]=await Promise.all([db().collection("sms_messages").orderBy("createdAt","desc").limit(100).get(),db().collection("sms_settings").get()]);return{messages:messages.docs.map(d=>d.data()),suspendedUsers:settings.docs.filter(d=>d.data().suspended).length}}
