import type { DnsRecord, DomainDetails, Registrant, ResellerClubOptions } from "@/types/domains";

const config = (): ResellerClubOptions | null => process.env.RESELLERCLUB_RESELLER_ID && process.env.RESELLERCLUB_API_KEY && process.env.RESELLERCLUB_BASE_URL ? { resellerId: process.env.RESELLERCLUB_RESELLER_ID, apiKey: process.env.RESELLERCLUB_API_KEY, baseUrl: process.env.RESELLERCLUB_BASE_URL.replace(/\/$/, "") } : null;
async function call<T>(endpoint: string, params: Record<string, string | number | undefined>): Promise<T> { const c = config(); if (!c) throw new Error("Domain registration is not configured."); const url = new URL(`${c.baseUrl}/${endpoint.replace(/^\//, "")}`); url.searchParams.set("auth-userid", c.resellerId); url.searchParams.set("api-key", c.apiKey); Object.entries(params).forEach(([k, v]) => v !== undefined && url.searchParams.set(k, String(v))); const response = await fetch(url, { cache: "no-store", signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error("Registrar request failed."); const data = await response.json().catch(() => null); if (!data || data.error) throw new Error("Registrar request failed."); return data as T; }
export function isResellerClubConfigured() { return Boolean(config()); }
export async function checkAvailability(domain: string) { const data = await call<Record<string, { status?: string }>>("domains/available.json", { "domain-name": domain, "tlds": domain.split(".").slice(1).join(".") }); const entry = data[domain] ?? Object.values(data)[0]; return entry?.status === "available"; }
export async function registerDomain(input: { domain: string; years: number; registrant: Registrant; nameservers?: string[] }) { return call<{ entityid?: string }>("domains/register.json", { "domain-name": input.domain, years: input.years, "name": input.registrant.name, "email": input.registrant.email, "phone-cc": "234", "phone": input.registrant.phone, "customer-id": undefined, ns: input.nameservers?.join(",") }); }
export async function renewDomain(domain: string, years = 1) { return call<{ entityid?: string }>("domains/renew.json", { "domain-name": domain, years }); }
export async function getDomainDetails(domain: string): Promise<DomainDetails> { const data = await call<Record<string, unknown>>("domains/details.json", { "domain-name": domain }); return { domain, status: String(data.status ?? "active"), expiryDate: typeof data.expirydate === "string" ? data.expirydate : null, nameservers: Array.isArray(data.nameservers) ? data.nameservers.map(String) : [], dnsRecords: [] }; }
export async function updateNameservers(domain: string, nameservers: string[]) { return call("domains/modify-ns.json", { "domain-name": domain, ns: nameservers.join(",") }); }
export async function getDnsRecords(domain: string): Promise<DnsRecord[]> { const data = await call<{ records?: DnsRecord[] }>("dns/manage-records.json", { "domain-name": domain }); return data.records ?? []; }
export async function updateDnsRecords(domain: string, records: DnsRecord[]) { return call("dns/manage-records.json", { "domain-name": domain, records: JSON.stringify(records) }); }
