"use client";
import { FormEvent, useEffect, useState } from "react";
import { SupportSitePreview } from "./support-site-preview";
import { getPublishedSupportSite, saveSupportTicket } from "@/lib/support-sites/store";
import type { SupportSite } from "@/lib/support-sites/types";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function PublishedSupportSite({slug}:{slug:string}){const [site,setSite]=useState<SupportSite|null>();const [sent,setSent]=useState(false);useEffect(()=>{getPublishedSupportSite(slug).then(setSite)},[slug]);if(site===undefined)return <div className="grid min-h-screen place-items-center">Loading help center…</div>;if(!site)return <div className="grid min-h-screen place-items-center"><div className="text-center"><h1 className="text-3xl font-semibold">This support site is not published.</h1><p className="mt-2 text-muted-foreground">Check the address or contact the site owner.</p></div></div>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const forbidden=/password|seed phrase|private key|2fa|otp|pin|card number/i;const message=String(f.get("message")||"");if(forbidden.test(message)){alert("Please remove passwords, security codes, financial credentials, or recovery phrases.");return}await saveSupportTicket({id:`ticket_${Date.now()}`,siteId:site!.id,ownerId:site!.userId,name:String(f.get("name")),email:String(f.get("email")),subject:String(f.get("subject")),category:String(f.get("category")),message,status:"open",createdAt:new Date().toISOString()});setSent(true);e.currentTarget.reset()}
 return <><SupportSitePreview site={site}/><section className="border-t bg-muted/30 px-4 py-16"><form onSubmit={submit} className="mx-auto max-w-2xl space-y-4 rounded-3xl border bg-background p-7 shadow-sm"><div><h2 className="text-2xl font-semibold">Submit a support ticket</h2><p className="mt-1 text-sm text-muted-foreground">Never include passwords, OTPs, recovery phrases, keys, or financial credentials.</p></div>{sent&&<p className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-700">Your ticket was submitted.</p>}<div className="grid gap-4 sm:grid-cols-2"><Input required name="name" placeholder="Name"/><Input required type="email" name="email" placeholder="Email"/></div><Input required name="subject" placeholder="Subject"/><Input required name="category" placeholder="Category"/><textarea required name="message" placeholder="How can we help?" className="min-h-32 w-full rounded-xl border bg-background p-3 text-sm"/><Button type="submit">Submit ticket</Button></form></section></>}
