"use client";

import * as React from "react";
import { ArrowRight, BookOpen, ChevronDown, Clock3, Headphones, Mail, MapPin, MessageCircle, Search, ShieldCheck, Sparkles } from "lucide-react";
import type { SupportSite } from "@/lib/support-sites/types";

function SearchBox({ site, query, setQuery, dark = false }: { site: SupportSite; query: string; setQuery: (value: string) => void; dark?: boolean }) {
  const results = query.trim() ? [...site.articles.map((a) => ({ title: a.title, body: a.content, kind: "Article" })), ...site.faqs.map((f) => ({ title: f.question, body: f.answer, kind: "FAQ" }))].filter((item) => `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : [];
  return <div className="relative mx-auto mt-7 max-w-2xl"><Search className={`absolute left-5 top-1/2 size-5 -translate-y-1/2 ${dark ? "text-white/40" : "opacity-40"}`} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={site.searchPlaceholder} style={{ borderRadius: `${site.branding.radius}px` }} className={`w-full border px-14 py-4 shadow-xl outline-none ${dark ? "border-white/10 bg-white/10 text-white placeholder:text-white/40" : "border-black/10 bg-white text-slate-900"}`} />{query && <div style={{ borderRadius: `${site.branding.radius}px` }} className="absolute inset-x-0 top-full z-20 mt-2 bg-white p-2 text-left text-slate-900 shadow-2xl">{results.length ? results.map((r) => <div key={`${r.kind}-${r.title}`} className="rounded-lg p-3 hover:bg-slate-50"><span className="text-xs text-slate-400">{r.kind}</span><div className="font-medium">{r.title}</div></div>) : <p className="p-3 text-sm text-slate-500">No results found.</p>}</div>}</div>;
}

function Header({ site, dark = false, corporate = false, apple = false, binance = false }: { site: SupportSite; dark?: boolean; corporate?: boolean; apple?: boolean; binance?: boolean }) {
  const binanceItems = ["Buy Crypto", "Markets", "Trade", "Futures", "Earn", "Square", "More"];
  const appleItems = ["Store", "Mac", "iPad", "iPhone", "Watch", "Vision", "AirPods", "TV & Home", "Entertainment", "Accessories", "Support"];
  return <header className={`flex items-center justify-between border-b px-6 py-5 lg:px-10 ${dark ? "border-white/10" : "border-black/10"}`}><div className="flex items-center gap-3 font-semibold tracking-tight">{site.branding.logoUrl ? <img src={site.branding.logoUrl} alt="" className="size-8 rounded object-contain" /> : <span style={{ background: site.branding.primary, borderRadius: `${site.branding.radius}px` }} className="flex size-9 items-center justify-center text-white"><Headphones className="size-4" /></span>}<span>{site.branding.businessName}</span></div><nav className={`hidden items-center gap-5 text-xs md:flex `}>{binance ? <>{binanceItems.map((item) => <span key={item} className="whitespace-nowrap">{item}</span>)}<span className="whitespace-nowrap">⌕ Search</span><span className="whitespace-nowrap">Log In</span><span className="rounded-md bg-[#f0b90b] px-3 py-2 font-semibold text-[#181a20]">Sign Up</span></> : apple ? appleItems.map((item) => <span key={item} className="whitespace-nowrap">{item}</span>) : <><span>{corporate ? "About" : "Home"}</span><span>{corporate ? "Contact Us" : "Help Center"}</span><span>{corporate ? "News" : "Guides"}</span>{!corporate && <span>FAQs</span>}</>}</nav><button type="button" className="rounded-full border px-4 py-2 text-sm md:hidden">Menu</button></header>;
}

function GenericPreview({ site, compact }: { site: SupportSite; compact: boolean }) {
  const [query, setQuery] = React.useState("");
  const [openFaq, setOpenFaq] = React.useState<string | null>(null);
  const enabled = (id: SupportSite["sections"][number]["id"]) => site.sections.find((s) => s.id === id)?.enabled;
  return <><Header site={site} /><section className={`${compact ? "px-4 py-8" : "px-6 py-16 lg:px-10 lg:py-20"} text-center`} style={{ background: `linear-gradient(135deg, ${site.branding.primary}18, ${site.branding.secondary}22)` }}><span className="text-xs font-semibold uppercase tracking-[0.22em] opacity-60">Support center</span><h1 className={`${compact ? "mt-2 text-2xl" : "mt-3 text-4xl md:text-5xl"} font-semibold tracking-tight`}>{site.heroTitle}</h1><p className="mx-auto mt-3 max-w-xl opacity-65">{site.heroSubtitle}</p>{enabled("search") && <SearchBox site={site} query={query} setQuery={setQuery} />}</section><main className={`${compact ? "space-y-8 px-4 py-8" : "mx-auto max-w-6xl space-y-16 px-6 py-14 lg:px-10"}`}>{enabled("topics") && <section><SectionLabel site={site}>Popular topics</SectionLabel><h2 className="mt-1 text-2xl font-semibold">Start with a topic</h2><div className={`mt-5 grid gap-3 ${compact ? "grid-cols-2" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{site.categories.map((category, i) => <div key={category} style={{ borderRadius: `${site.branding.radius}px` }} className="border border-current/10 p-4"><span style={{ color: site.branding.primary }} className="text-sm font-semibold">0{i + 1}</span><h3 className="mt-3 font-medium">{category}</h3><p className="mt-1 text-sm opacity-55">Helpful guides and answers</p></div>)}</div></section>}{enabled("knowledge") && <ArticleList site={site} compact={compact} />}{enabled("faq") && <section><SectionLabel site={site}>Quick answers</SectionLabel><h2 className="mt-1 text-2xl font-semibold">Frequently asked questions</h2><div className="mt-5 space-y-2">{site.faqs.map((faq) => <button key={faq.id} type="button" onClick={() => setOpenFaq(openFaq === faq.id ? null : faq.id)} style={{ borderRadius: `${site.branding.radius}px` }} className="w-full border border-current/10 p-4 text-left"><span className="flex items-center justify-between gap-3 font-medium">{faq.question}<ChevronDown className={`size-4 transition-transform ${openFaq === faq.id ? "rotate-180" : ""}`} /></span>{openFaq === faq.id && <p className="mt-3 text-sm leading-6 opacity-60">{faq.answer}</p>}</button>)}</div></section>}{enabled("contact") && <ContactBlock site={site} />}{enabled("hours") && <div className="flex items-center gap-3 text-sm opacity-60"><Clock3 className="size-4" />{site.contact.businessHours}</div>}</main><Footer site={site} /></>;
}

function SectionLabel({ site, children }: { site: SupportSite; children: React.ReactNode }) { return <span className="text-sm font-medium" style={{ color: site.branding.primary }}>{children}</span>; }
function ArticleList({ site, compact }: { site: SupportSite; compact: boolean }) { return <section><SectionLabel site={site}>Knowledge base</SectionLabel><h2 className="mt-1 text-2xl font-semibold">Latest guides</h2><div className="mt-5 divide-y divide-current/10">{site.articles.slice(0, compact ? 3 : 5).map((article) => <article key={article.id} className="flex items-center justify-between gap-4 py-4"><div><span className="text-xs opacity-45">{article.category}</span><h3 className="font-medium">{article.title}</h3><p className="mt-1 text-sm opacity-55">{article.description}</p></div><ArrowRight className="size-4 opacity-35" /></article>)}</div></section>; }
function ContactBlock({ site }: { site: SupportSite }) { return <section style={{ borderRadius: `${site.branding.radius}px`, background: site.branding.primary, color: "white" }} className="flex flex-col justify-between gap-6 p-8 md:flex-row md:items-center"><div><h2 className="text-2xl font-semibold">Still need a hand?</h2><p className="mt-2 opacity-75">Our support team is ready to help.</p></div><div className="flex flex-wrap gap-2">{site.contact.enabled.email && <a href={`mailto:${site.contact.email}`} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-medium text-slate-900"><Mail className="size-4" /> Send email</a>}{site.contact.enabled.liveChat && <a href={site.contact.liveChatUrl || "#ticket"} className="inline-flex items-center gap-2 rounded-full border border-white/30 px-4 py-2 text-sm font-medium"><MessageCircle className="size-4" /> Start live chat</a>}</div></section>; }
function Footer({ site }: { site: SupportSite }) { return <footer className="flex flex-col justify-between gap-3 border-t border-current/10 px-6 py-8 text-sm opacity-60 lg:px-10 sm:flex-row"><span>© {new Date().getFullYear()} {site.branding.businessName}</span><span className="inline-flex items-center gap-1"><ShieldCheck className="size-4" /> We never ask for passwords or security codes.</span></footer>; }

function AppleDeviceImage({ category }: { category: string }) {
  const label = category.toLowerCase();
  const src = label.includes("iphone") ? "/support-templates/apple-devices/iphone.jpg" : label.includes("ipad") ? "/support-templates/apple-devices/ipad.jpg" : label.includes("watch") ? "/support-templates/apple-devices/watch.jpg" : label.includes("mac") ? "/support-templates/apple-devices/mac.jpg" : label.includes("airpod") ? "/support-templates/apple-devices/airpods.jpg" : label.includes("vision") ? "/support-templates/apple-devices/vision-pro.jpg" : "/support-templates/apple-devices/iphone.jpg";
  return <img src={src} alt={`${category} device`} className="size-16 object-contain mix-blend-multiply" />;
}

function AppleLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <><Header site={site} apple /><section className="px-6 py-16 text-center lg:py-24"><h1 className="text-5xl font-semibold tracking-tight">{site.heroTitle}</h1><p className="mx-auto mt-4 max-w-xl text-lg opacity-70">{site.heroSubtitle}</p><SearchBox site={site} query={query} setQuery={setQuery} /></section><main className="mx-auto max-w-6xl space-y-20 px-6 py-10 lg:px-10"><section><h2 className="text-center text-3xl font-semibold">Get Support</h2><div className="mt-10 grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-6">{site.categories.map((category) => <div key={category} className="group text-center"><div style={{ background: `${site.branding.primary}12`, color: site.branding.primary }} className="mx-auto flex size-20 items-center justify-center overflow-hidden rounded-3xl transition-transform group-hover:-translate-y-1"><AppleDeviceImage category={category} /></div><p className="mt-3 text-sm font-medium">{category}</p></div>)}</div></section><section><h2 className="text-3xl font-semibold">Popular Topics</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{site.articles.slice(0, 6).map((article) => <div key={article.id} className="rounded-2xl bg-[#f5f5f7] p-6"><h3 className="font-semibold">{article.title}</h3><p className="mt-2 text-sm opacity-70">{article.description}</p><button className="mt-5 text-sm font-medium" style={{ color: site.branding.primary }}>Learn more →</button></div>)}</div></section><ContactBlock site={site} /></main><Footer site={site} /></>; }

function BinanceLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <div className="bg-[#0b0e11] text-[#eaecef]"><Header site={site} dark binance /><section className="px-6 py-20 text-center"><h1 className="text-4xl font-semibold md:text-5xl">{site.heroTitle}</h1><p className="mx-auto mt-4 max-w-xl text-[#848e9c]">{site.heroSubtitle}</p><SearchBox site={site} query={query} setQuery={setQuery} dark /></section><main className="mx-auto max-w-6xl space-y-16 px-6 py-12 lg:px-10"><section><h2 className="text-2xl font-semibold">Popular Topics</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{site.categories.map((category) => <div key={category} className="rounded-xl border border-white/10 bg-[#181a20] p-5 font-medium transition-colors hover:border-[#f0b90b]/60"><span className="mr-3 text-[#f0b90b]">•</span>{category}</div>)}</div></section><section><h2 className="text-2xl font-semibold">Frequently Asked Questions</h2><div className="mt-6 space-y-3">{site.faqs.map((faq) => <div key={faq.id} className="rounded-xl border border-white/10 bg-[#181a20] p-5"><h3 className="font-medium">{faq.question}</h3><p className="mt-2 text-sm leading-6 text-[#848e9c]">{faq.answer}</p></div>)}</div></section><section><h2 className="text-2xl font-semibold">Browse Help Topics</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{site.categories.map((category, i) => <div key={`${category}-browse`} className="rounded-xl bg-[#181a20] p-6"><h3 className="font-semibold text-[#f0b90b]">{category}</h3><ul className="mt-4 space-y-2 text-sm text-[#848e9c]">{site.articles.slice(i % 2, (i % 2) + 3).map((a) => <li key={a.id}>• {a.title}</li>)}</ul></div>)}</div></section><ContactBlock site={site} /></main><Footer site={site} /></div>; }

function BydLayout({ site }: { site: SupportSite }) { return <><Header site={site} corporate /><section className="relative isolate overflow-hidden px-6 py-28 text-white lg:px-16 lg:py-40"><img src="/support-templates/byd-showroom.webp" alt="BYD showroom" className="absolute inset-0 -z-20 size-full object-cover object-center" /><div className="absolute inset-0 -z-10 bg-black/55" /><div className="relative mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-red-300">BYD Global</p><h1 className="mt-5 text-5xl font-semibold uppercase tracking-tight md:text-7xl">CONTACT US</h1><p className="mt-6 max-w-2xl text-lg font-medium uppercase tracking-[0.12em] text-white/85">CONNECT WITH US, YOUR SATISFACTION STARTS HERE</p></div></section><main className="mx-auto max-w-6xl px-6 py-16 lg:px-10"><h2 className="text-3xl font-semibold">Global Headquarters</h2><p className="mt-3 text-muted-foreground">BYD Company Limited · Customer support and product enquiries</p><div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{site.categories.map((category, i) => <div key={category} className="border-t-2 border-red-600 pt-5"><MapPin className="size-5 text-red-600" /><h3 className="mt-4 text-xl font-semibold">{category}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{i === 0 ? "Online support headquarters" : "Find customer service, technical help, and local assistance for your account."}</p><p className="mt-5 text-sm font-medium">Customer Service</p><p className="text-sm text-muted-foreground">Monday to Saturday · 9:00am–6:00pm</p></div>)}</div><ContactBlock site={site} /></main><Footer site={site} /></>; }

function BitcoinLayout({ site }: { site: SupportSite }) { return <><Header site={site} /><section className="mx-auto max-w-5xl px-6 py-16 text-center"><h1 className="text-4xl font-semibold tracking-tight md:text-5xl">{site.heroTitle}</h1><p className="mx-auto mt-4 max-w-xl text-lg opacity-65">{site.heroSubtitle}</p><div className="mx-auto mt-10 max-w-2xl"><SearchBox site={site} query={""} setQuery={() => undefined} /></div></section><main className="mx-auto max-w-5xl px-6 pb-20"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{site.categories.map((category, i) => <article key={category} className="rounded-2xl border bg-white p-6 shadow-sm transition-shadow hover:shadow-lg"><div style={{ background: `${site.branding.primary}16`, color: site.branding.primary }} className="flex size-12 items-center justify-center rounded-xl"><BookOpen className="size-6" /></div><h2 className="mt-5 text-lg font-semibold">{category}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Learn how to use Bitcoin.com {category.toLowerCase()}.</p><p className="mt-5 text-xs text-muted-foreground">{i + 1} author · {i * 6 + 5} articles</p></article>)}</div><div className="mt-16 flex items-center justify-between border-t pt-8"><span className="font-semibold">{site.branding.businessName}</span><span className="text-sm text-muted-foreground">Download the app · English</span></div></main></>; }

function BitsoLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <><Header site={site} /><section className="px-6 py-20 text-center"><h1 className="text-5xl font-semibold tracking-tight">{site.heroTitle}</h1><p className="mx-auto mt-4 max-w-lg text-lg opacity-65">{site.heroSubtitle}</p><SearchBox site={site} query={query} setQuery={setQuery} /></section><main className="mx-auto max-w-3xl px-6 pb-20"><div className="rounded-3xl bg-[#f7f7fb] p-8 text-center"><MessageCircle className="mx-auto size-8" style={{ color: site.branding.primary }} /><h2 className="mt-4 text-2xl font-semibold">Didn&apos;t find what you were looking for?</h2><p className="mt-3 text-sm text-muted-foreground">For a faster and more efficient service, open a chat where an expert will assist you.</p><button className="mt-6 rounded-full px-6 py-3 text-sm font-semibold text-white" style={{ background: site.branding.primary }}>Open a chat</button></div><h2 className="mt-16 text-2xl font-semibold">Promoted articles</h2><div className="mt-5 divide-y">{site.articles.map((article) => <article key={article.id} className="flex items-center justify-between py-5"><div><p className="font-medium">{article.title}</p><p className="mt-1 text-sm text-muted-foreground">{article.description}</p></div><ArrowRight className="size-4 text-muted-foreground" /></article>)}</div></main><Footer site={site} /></>; }

function ChangellyLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <><Header site={site} /><section className="bg-[#fafafa] px-6 py-16 text-center"><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: site.branding.primary }}>Changelly Knowledge Base</p><h1 className="mt-4 text-4xl font-semibold">{site.heroTitle}</h1><SearchBox site={site} query={query} setQuery={setQuery} /></section><main className="mx-auto max-w-6xl space-y-14 px-6 py-14 lg:px-10"><section className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{site.categories.map((category, i) => <div key={category}><h2 className="text-lg font-semibold">{category}</h2><div className="mt-4 space-y-3">{site.articles.slice(i % 3, (i % 3) + 3).map((article) => <a key={article.id} href="#article" className="block text-sm text-muted-foreground hover:text-foreground">{article.title}</a>)}</div><button className="mt-4 text-xs font-bold uppercase" style={{ color: site.branding.primary }}>See other articles →</button></div>)}</section><div className="rounded-2xl border bg-white p-8 text-center"><h2 className="text-2xl font-semibold">Can&apos;t find what you&apos;re looking for?</h2><p className="mt-2 text-muted-foreground">Let us help you.</p><button className="mt-5 rounded-full px-6 py-3 text-sm font-semibold text-white" style={{ background: site.branding.primary }}>Submit a ticket</button></div></main><Footer site={site} /></>; }

function CashAppLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <><Header site={site} /><section className="bg-[#00d64f] px-6 py-20 text-center text-black"><p className="text-sm font-semibold">Personalized help is one step away</p><h1 className="mt-4 text-5xl font-semibold tracking-tight">{site.heroTitle}</h1><SearchBox site={site} query={query} setQuery={setQuery} /></section><main className="mx-auto max-w-6xl px-6 py-16 lg:px-10"><section><h2 className="text-2xl font-semibold">Popular Topics</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{site.articles.slice(0, 6).map((article) => <div key={article.id} className="rounded-xl bg-[#f5f5f5] p-5 font-medium">{article.title}</div>)}</div></section><section className="mt-16"><h2 className="text-2xl font-semibold">Browse</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{site.categories.map((category) => <div key={category} className="flex items-center justify-between border-b py-4 font-medium"><span>{category}</span><ArrowRight className="size-4" /></div>)}</div></section><div className="mt-16 rounded-2xl bg-black p-8 text-white"><h2 className="text-2xl font-semibold">Contact us</h2><p className="mt-2 text-white/65">Start a chat in your Cash App account for fast support.</p><button className="mt-5 rounded-full bg-[#00d64f] px-5 py-3 text-sm font-semibold text-black">Start a chat</button></div></main><Footer site={site} /></>; }

function BlockchainLayout({ site }: { site: SupportSite }) { const [query, setQuery] = React.useState(""); return <><Header site={site} /><section className="bg-[#f7f9fc] px-6 py-16 text-center"><h1 className="text-4xl font-semibold">{site.heroTitle}</h1><p className="mt-3 text-muted-foreground">{site.branding.businessName}</p><SearchBox site={site} query={query} setQuery={setQuery} /></section><main className="mx-auto max-w-6xl space-y-16 px-6 py-14 lg:px-10"><section className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-[#eaf0ff] p-7"><div className="flex size-12 items-center justify-center rounded-xl bg-[#1652f0] text-white"><Sparkles className="size-6" /></div><h2 className="mt-5 text-xl font-semibold">Blockchain.com Wallet</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Manage your Blockchain.com wallet and trading account.</p></div><div className="rounded-2xl bg-[#eef8ff] p-7"><div className="flex size-12 items-center justify-center rounded-xl bg-[#4c8bf5] text-white"><ShieldCheck className="size-6" /></div><h2 className="mt-5 text-xl font-semibold">Security & Account</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep your Blockchain.com account protected.</p></div></section><section><h2 className="text-2xl font-semibold">Featured articles</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{site.articles.map((article) => <article key={article.id} className="rounded-2xl border bg-white p-6"><span className="text-xs font-semibold" style={{ color: site.branding.primary }}>{article.category}</span><h3 className="mt-2 font-semibold">{article.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{article.description}</p><a href="#article" className="mt-5 inline-block text-sm font-medium" style={{ color: site.branding.primary }}>Read article →</a></article>)}</div></section><section><h2 className="text-2xl font-semibold">Frequently asked questions</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{site.faqs.map((faq) => <div key={faq.id} className="rounded-xl border bg-white p-5 font-medium">{faq.question}</div>)}</div></section><ContactBlock site={site} /></main><Footer site={site} /></>; }

export function SupportSitePreview({ site, compact = false }: { site: SupportSite; compact?: boolean }) {
  const variant = site.templateId;
  return <div style={{ background: site.branding.background, color: site.branding.text, fontFamily: `${site.branding.font}, ui-sans-serif, system-ui` }} className="min-h-full overflow-hidden">{variant === "aura-fintech" ? <AppleLayout site={site} /> : variant === "orbit-crypto-saas" ? <BinanceLayout site={site} /> : variant === "routecare" ? <BydLayout site={site} /> : variant === "cartwise" ? <BitcoinLayout site={site} /> : variant === "clarity-docs" ? <BitsoLayout site={site} /> : variant === "summit-corporate" ? <ChangellyLayout site={site} /> : variant === "plainhelp" ? <CashAppLayout site={site} /> : variant === "nightshift" ? <BlockchainLayout site={site} /> : <GenericPreview site={site} compact={compact} />}</div>;
}
