"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Eye, Plus, Save, Trash2 } from "lucide-react";
import { useAuth } from "@/context/auth-context";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SupportSitePreview } from "./support-site-preview";
import { createSupportSite } from "@/lib/support-sites/templates";
import { getSupportSite, getSupportTemplate, saveSupportSite } from "@/lib/support-sites/store";
import type { SupportSite } from "@/lib/support-sites/types";

const tabs = ["Branding","Content","Sections","FAQs","Contact","SEO"] as const;
export function SupportEditor({ templateId, siteId }: { templateId: string; siteId?: string }) {
  const { user, loading } = useAuth(); const router=useRouter();
  const [site,setSite]=useState<SupportSite>(()=>createSupportSite(templateId,"guest"));
  const [tab,setTab]=useState<(typeof tabs)[number]>("Branding"); const [saved,setSaved]=useState(false);
  useEffect(()=>{ if(!loading&&!user) router.replace(`/auth/login?next=/support-templates/${templateId}/editor`); },[loading,user,router,templateId]);
  useEffect(()=>{ if(user) { if(siteId) getSupportSite(siteId).then(found=>{if(found&&(found.userId===user.uid||user.role==="admin"))setSite(found)}); else getSupportTemplate(templateId).then(template=>setSite(createSupportSite(templateId,user.uid,template?[template]:undefined))); } },[user,siteId,templateId]);
  const update=(patch:Partial<SupportSite>)=>{setSite(s=>({...s,...patch}));setSaved(false)};
  const branding=(key:keyof SupportSite["branding"],value:string|number)=>update({branding:{...site.branding,[key]:value}});
  const contact=(key:keyof SupportSite["contact"],value:unknown)=>update({contact:{...site.contact,[key]:value}});
  const save=async()=>{if(!user)return; const next={...site,userId:siteId?site.userId:user.uid};await saveSupportSite(next);setSite(next);setSaved(true);router.replace(`/support-templates/${templateId}/editor?site=${next.id}`)};
  const panel=(()=>{
    if(tab==="Branding") return <><Field label="Business name" value={site.branding.businessName} onChange={v=>branding("businessName",v)}/><Field label="Logo URL" value={site.branding.logoUrl} onChange={v=>branding("logoUrl",v)}/><Field label="Primary color" type="color" value={site.branding.primary} onChange={v=>branding("primary",v)}/><Field label="Background" type="color" value={site.branding.background} onChange={v=>branding("background",v)}/><Field label="Text color" type="color" value={site.branding.text} onChange={v=>branding("text",v)}/><Field label="Font" value={site.branding.font} onChange={v=>branding("font",v)}/><Field label="Border radius" type="number" value={String(site.branding.radius)} onChange={v=>branding("radius",Number(v))}/></>;
    if(tab==="Content") return <><Field label="Site name" value={site.name} onChange={v=>update({name:v})}/><Field label="Public slug" value={site.slug} onChange={v=>update({slug:v.toLowerCase().replace(/[^a-z0-9-]/g,"-")})}/><Field label="Hero title" value={site.heroTitle} onChange={v=>update({heroTitle:v})}/><Field label="Hero subtitle" value={site.heroSubtitle} onChange={v=>update({heroSubtitle:v})}/><Field label="Search placeholder" value={site.searchPlaceholder} onChange={v=>update({searchPlaceholder:v})}/></>;
    if(tab==="Sections") return <div className="space-y-2">{site.sections.map((section,i)=><div key={section.id} className="flex items-center gap-2 rounded-xl border p-3"><input type="checkbox" checked={section.enabled} onChange={()=>update({sections:site.sections.map(s=>s.id===section.id?{...s,enabled:!s.enabled}:s)})}/><span className="flex-1 capitalize">{section.id}</span><Button size="icon" variant="ghost" disabled={!i} onClick={()=>{const a=[...site.sections];[a[i-1],a[i]]=[a[i],a[i-1]];update({sections:a})}}><ArrowUp className="size-4"/></Button><Button size="icon" variant="ghost" disabled={i===site.sections.length-1} onClick={()=>{const a=[...site.sections];[a[i],a[i+1]]=[a[i+1],a[i]];update({sections:a})}}><ArrowDown className="size-4"/></Button></div>)}</div>;
    if(tab==="FAQs") return <div className="space-y-3">{site.faqs.map((faq,i)=><div key={faq.id} className="rounded-xl border p-3"><Field label="Question" value={faq.question} onChange={v=>update({faqs:site.faqs.map(f=>f.id===faq.id?{...f,question:v}:f)})}/><Field label="Answer" value={faq.answer} onChange={v=>update({faqs:site.faqs.map(f=>f.id===faq.id?{...f,answer:v}:f)})}/><Button variant="ghost" size="sm" onClick={()=>update({faqs:site.faqs.filter(f=>f.id!==faq.id)})}><Trash2 className="size-4"/> Delete</Button></div>)}<Button variant="secondary" onClick={()=>update({faqs:[...site.faqs,{id:`faq-${Date.now()}`,question:"New question",answer:"Add your answer.",category:"General"}]})}><Plus className="size-4"/>Add FAQ</Button></div>;
    if(tab==="Contact") return <><Field label="Support email" value={site.contact.email} onChange={v=>contact("email",v)}/><Field label="Phone" value={site.contact.phone} onChange={v=>contact("phone",v)}/><Field label="WhatsApp URL" value={site.contact.whatsappUrl} onChange={v=>contact("whatsappUrl",v)}/><Field label="Telegram URL" value={site.contact.telegramUrl} onChange={v=>contact("telegramUrl",v)}/><Field label="Live chat URL" value={site.contact.liveChatUrl} onChange={v=>contact("liveChatUrl",v)}/><Field label="Business hours" value={site.contact.businessHours} onChange={v=>contact("businessHours",v)}/></>;
    return <><Field label="Site title" value={site.seo.title} onChange={v=>update({seo:{...site.seo,title:v}})}/><Field label="Meta description" value={site.seo.description} onChange={v=>update({seo:{...site.seo,description:v}})}/><Field label="Keywords" value={site.seo.keywords} onChange={v=>update({seo:{...site.seo,keywords:v}})}/></>;
  })();
  if(loading||!user)return <div className="grid min-h-screen place-items-center text-muted-foreground">Loading editor…</div>;
  return <div className="flex min-h-screen flex-col bg-muted/40"><header className="flex h-16 items-center justify-between border-b bg-background px-4"><div><p className="font-semibold">Support Website Studio</p><p className="text-xs text-muted-foreground">{saved?"All changes saved":"Unsaved changes"}</p></div><div className="flex gap-2"><Button variant="secondary" asChild><a href={`/s/${site.slug}`} target="_blank"><Eye className="size-4"/>Preview</a></Button><Button onClick={save}><Save className="size-4"/>Save project</Button></div></header><div className="grid flex-1 lg:grid-cols-[180px_minmax(0,1fr)_330px]"><aside className="border-r bg-background p-3">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`mb-1 w-full rounded-lg px-3 py-2 text-left text-sm ${tab===item?"bg-primary text-primary-foreground":"hover:bg-muted"}`}>{item}</button>)}</aside><main className="overflow-auto p-5"><div className="mx-auto min-h-[760px] max-w-5xl overflow-hidden rounded-2xl border bg-background shadow-xl"><SupportSitePreview site={site}/></div></main><aside className="border-l bg-background p-5"><h2 className="mb-5 font-semibold">{tab}</h2><div className="space-y-4">{panel}</div></aside></div></div>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-sm"><span className="mb-1.5 block text-muted-foreground">{label}</span><Input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
