"use client";

import * as React from "react";
import { BookOpen, ChevronDown, Clock3, Headphones, Mail, Search, ShieldCheck } from "lucide-react";
import type { SupportSite } from "@/lib/support-sites/types";

export function SupportSitePreview({ site, compact = false }: { site: SupportSite; compact?: boolean }) {
  const [query, setQuery] = React.useState("");
  const [openFaq, setOpenFaq] = React.useState<string | null>(null);
  const enabled = (id: SupportSite["sections"][number]["id"]) => site.sections.find((s) => s.id === id)?.enabled;
  const results = query.trim() ? [...site.articles.map(a => ({ title: a.title, body: a.content, kind: "Article" })), ...site.faqs.map(f => ({ title: f.question, body: f.answer, kind: "FAQ" }))].filter(item => `${item.title} ${item.body}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : [];
  const radius = `${site.branding.radius}px`;
  const borderRadius = radius;
  return (
    <div style={{ background: site.branding.background, color: site.branding.text, fontFamily: `${site.branding.font}, ui-sans-serif, system-ui` }} className="min-h-full overflow-hidden">
      <header className={`${compact ? "px-4 py-3" : "px-6 py-5 lg:px-10"} flex items-center justify-between border-b border-black/10`}>
        <div className="flex items-center gap-2 font-semibold">{site.branding.logoUrl ? <img src={site.branding.logoUrl} alt="" className="size-8 rounded object-contain" /> : <span style={{ background: site.branding.primary, borderRadius: radius }} className="flex size-8 items-center justify-center text-white"><Headphones className="size-4" /></span>}<span>{site.branding.businessName}</span></div>
        <nav className={`${compact ? "hidden" : "hidden md:flex"} items-center gap-6 text-sm opacity-75`}><span>Home</span><span>Help Center</span><span>Guides</span><span>FAQs</span><span>Contact</span></nav>
      </header>
      {enabled("hero") && <section className={`${compact ? "px-4 py-8" : "px-6 py-16 lg:px-10 lg:py-20"} text-center`} style={{ background: `linear-gradient(135deg, ${site.branding.primary}18, ${site.branding.secondary}22)` }}><span className="text-xs font-semibold uppercase tracking-[0.22em] opacity-60">Support center</span><h1 className={`${compact ? "mt-2 text-2xl" : "mt-3 text-4xl md:text-5xl"} font-semibold tracking-tight`}>{site.heroTitle}</h1><p className="mx-auto mt-3 max-w-xl opacity-65">{site.heroSubtitle}</p>{enabled("search") && <div className="relative mx-auto mt-7 max-w-xl"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 opacity-40" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={site.searchPlaceholder} style={{ borderRadius: radius }} className="w-full border border-black/10 bg-white px-12 py-4 text-slate-900 shadow-xl outline-none" />{query && <div style={{ borderRadius: radius }} className="absolute inset-x-0 top-full z-10 mt-2 bg-white p-2 text-left text-slate-900 shadow-2xl">{results.length ? results.map(r => <div key={`${r.kind}-${r.title}`} className="rounded-lg p-3 hover:bg-slate-50"><span className="text-xs text-slate-400">{r.kind}</span><div className="font-medium">{r.title}</div></div>) : <p className="p-3 text-sm text-slate-500">No results found.</p>}</div>}</div>}</section>}
      <main className={`${compact ? "space-y-8 px-4 py-8" : "mx-auto max-w-6xl space-y-16 px-6 py-14 lg:px-10"}`}>
        {enabled("topics") && <section><div className="flex items-end justify-between"><div><span className="text-sm font-medium" style={{ color: site.branding.primary }}>Popular topics</span><h2 className="mt-1 text-2xl font-semibold">Start with a topic</h2></div><BookOpen className="size-5 opacity-30" /></div><div className={`mt-5 grid gap-3 ${compact ? "grid-cols-2" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{site.categories.map((category, i) => <div key={category} style={{ borderRadius, background: "color-mix(in srgb, currentColor 4%, transparent)" }} className="border border-current/10 p-4"><span style={{ color: site.branding.primary }} className="text-sm font-semibold">0{i + 1}</span><h3 className="mt-3 font-medium">{category}</h3><p className="mt-1 text-sm opacity-55">Helpful guides and answers</p></div>)}</div></section>}
        {enabled("knowledge") && <section><span className="text-sm font-medium" style={{ color: site.branding.primary }}>Knowledge base</span><h2 className="mt-1 text-2xl font-semibold">Latest guides</h2><div className="mt-5 divide-y divide-current/10">{site.articles.slice(0, compact ? 3 : 5).map(article => <article key={article.id} className="flex items-center justify-between gap-4 py-4"><div><span className="text-xs opacity-45">{article.category}</span><h3 className="font-medium">{article.title}</h3><p className="mt-1 text-sm opacity-55">{article.description}</p></div><span className="text-lg opacity-35">→</span></article>)}</div></section>}
        {enabled("faq") && <section><span className="text-sm font-medium" style={{ color: site.branding.primary }}>Quick answers</span><h2 className="mt-1 text-2xl font-semibold">Frequently asked questions</h2><div className="mt-5 space-y-2">{site.faqs.map(faq => <button key={faq.id} type="button" onClick={() => setOpenFaq(openFaq === faq.id ? null : faq.id)} style={{ borderRadius }} className="w-full border border-current/10 p-4 text-left"><span className="flex items-center justify-between gap-3 font-medium">{faq.question}<ChevronDown className={`size-4 transition-transform ${openFaq === faq.id ? "rotate-180" : ""}`} /></span>{openFaq === faq.id && <p className="mt-3 text-sm leading-6 opacity-60">{faq.answer}</p>}</button>)}</div></section>}
        {enabled("contact") && <section style={{ borderRadius, background: site.branding.primary, color: "white" }} className={`${compact ? "p-5" : "p-8 md:p-10"} flex flex-col justify-between gap-6 md:flex-row md:items-center`}><div><h2 className="text-2xl font-semibold">Still need a hand?</h2><p className="mt-2 opacity-75">Our support team is ready to help.</p></div><div className="flex flex-wrap gap-2">{site.contact.enabled.email && <a href={`mailto:${site.contact.email}`} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-medium text-slate-900"><Mail className="size-4" /> Send email</a>}{site.contact.enabled.liveChat && <a href={site.contact.liveChatUrl || "#ticket"} className="inline-flex items-center gap-2 rounded-full border border-white/30 px-4 py-2 text-sm font-medium"><Headphones className="size-4" /> Start live chat</a>}</div></section>}
        {enabled("hours") && <div className="flex items-center gap-3 text-sm opacity-60"><Clock3 className="size-4" />{site.contact.businessHours}</div>}
      </main>
      {enabled("footer") && <footer className={`${compact ? "px-4 py-6" : "px-6 py-8 lg:px-10"} flex flex-col justify-between gap-3 border-t border-current/10 text-sm opacity-60 sm:flex-row`}><span>© {new Date().getFullYear()} {site.branding.businessName}</span><span className="inline-flex items-center gap-1"><ShieldCheck className="size-4" /> We never ask for passwords or security codes.</span></footer>}
    </div>
  );
}
