"use client";
import * as React from "react";
import Link from "next/link";
import { Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { getAuthHeaders } from "@/lib/licensing/client-auth";
import { useRequireAdmin } from "@/hooks/use-require-admin";
import type { Wallet, WalletTransaction } from "@/lib/wallet/types";

type AdminWallet = Wallet & { name?: string; email?: string };
type AdminData = { wallets: AdminWallet[]; transactions: WalletTransaction[]; summary: Record<string, number> };
const money = (n: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(n / 100);

export default function AdminWalletsPage() {
  const { isAdmin, loading: authLoading } = useRequireAdmin();
  const [data, setData] = React.useState<AdminData | null>(null); const [query, setQuery] = React.useState("");
  const [target, setTarget] = React.useState(""); const [direction, setDirection] = React.useState("credit"); const [amount, setAmount] = React.useState(5000); const [reason, setReason] = React.useState(""); const [saving, setSaving] = React.useState(false);
  const load = React.useCallback(async () => { const headers = await getAuthHeaders(); const response = await fetch("/api/wallet/admin/summary", { headers, cache: "no-store" }); const next = await response.json(); if (!response.ok) throw new Error(next.error); setData(next); }, []);
  React.useEffect(() => { if (isAdmin) load().catch((error) => toast.error(error.message)); }, [isAdmin, load]);
  async function adjustment() { setSaving(true); try { const headers = await getAuthHeaders(); const response = await fetch("/api/wallet/admin/adjustments", { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ targetUserId: target, direction, amountMinor: Math.round(amount * 100), reason }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); toast.success("Immutable adjustment recorded."); setReason(""); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Adjustment failed."); } finally { setSaving(false); } }
  async function refund(transaction: WalletTransaction) { const refundReason = window.prompt("Reason for this full refund?"); if (!refundReason) return; try { const headers = await getAuthHeaders(); const response = await fetch("/api/wallet/admin/refunds", { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ transactionId: transaction.id, reason: refundReason }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); toast.success("Refund credited and audit log recorded."); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Refund failed."); } }
  if (authLoading || !isAdmin || !data) return <div className="flex justify-center py-24"><Loader2 className="animate-spin" /></div>;
  const needle = query.toLowerCase(); const wallets = data.wallets.filter((wallet) => !needle || [wallet.userId, wallet.name, wallet.email].some((value) => value?.toLowerCase().includes(needle)) || data.transactions.some((tx) => tx.userId === wallet.userId && tx.reference.toLowerCase().includes(needle)));
  const cards = [["Wallet users", data.summary.walletUsers], ["Total balances", money(data.summary.totalBalancesMinor)], ["Deposits today", money(data.summary.depositsTodayMinor)], ["Deposits this month", money(data.summary.depositsMonthMinor)], ["Wallet spending", money(data.summary.spendingMinor)], ["Refunds", money(data.summary.refundsMinor)]];
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><Link href="/admin" className="text-sm text-primary">← Admin</Link><h1 className="mt-2 text-3xl font-semibold">Wallets</h1><p className="mt-1 text-muted-foreground">Balances, ledger activity, refunds, and controlled adjustments.</p>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div className="glass rounded-2xl p-5" key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section><input className="h-11 w-full rounded-xl border bg-background px-4" placeholder="Search name, email, user ID, or reference" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="mt-4 overflow-hidden rounded-2xl border">{wallets.map((wallet) => <button key={wallet.userId} onClick={() => setTarget(wallet.userId)} className="flex w-full items-center justify-between border-b p-4 text-left last:border-0 hover:bg-accent"><div><p className="font-medium">{wallet.name || wallet.email || wallet.userId}</p><p className="text-xs text-muted-foreground">{wallet.email ? `${wallet.email} · ` : ""}{wallet.userId}</p></div><p className="font-semibold">{money(wallet.balanceMinor)}</p></button>)}{wallets.length === 0 && <p className="p-10 text-center text-muted-foreground">No wallets found.</p>}</div></section>
      <aside className="h-fit rounded-2xl border bg-card p-5"><h2 className="font-semibold">Balance adjustment</h2><p className="mt-1 text-xs text-muted-foreground">Creates an immutable ledger entry and audit record.</p><label className="mt-5 block text-xs font-medium">Target user ID</label><input className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={target} onChange={(event) => setTarget(event.target.value)} /><label className="mt-4 block text-xs font-medium">Direction</label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={direction} onChange={(event) => setDirection(event.target.value)}><option value="credit">Credit</option><option value="debit">Debit</option></select><label className="mt-4 block text-xs font-medium">Amount (NGN)</label><input type="number" className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={amount} onChange={(event) => setAmount(Number(event.target.value))} /><label className="mt-4 block text-xs font-medium">Required reason</label><textarea className="mt-1 min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={reason} onChange={(event) => setReason(event.target.value)} /><Button className="mt-4 w-full" disabled={saving || !target || !reason || amount <= 0} onClick={adjustment}>{saving ? <Loader2 className="animate-spin" /> : "Record adjustment"}</Button></aside></div>
    <section className="mt-10"><h2 className="text-xl font-semibold">Recent wallet activity</h2><div className="mt-4 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-muted/50"><tr><th className="p-4">Date</th><th>User</th><th>Description</th><th>Reference</th><th>Amount</th><th>Action</th></tr></thead><tbody>{data.transactions.slice(0, 100).map((tx) => <tr key={tx.id} className="border-t"><td className="p-4">{new Date(tx.createdAt).toLocaleDateString()}</td><td className="font-mono text-xs">{tx.userId}</td><td>{tx.description}<span className="ml-2 text-xs capitalize text-muted-foreground">{tx.status}</span></td><td className="font-mono text-xs">{tx.reference}</td><td className={tx.direction === "credit" ? "text-emerald-600" : ""}>{tx.direction === "credit" ? "+" : "-"}{money(tx.amountMinor)}</td><td>{tx.type === "purchase" && tx.status === "completed" ? <Button size="sm" variant="secondary" onClick={() => refund(tx)}>Refund</Button> : "—"}</td></tr>)}</tbody></table></div></section>
  </main>;
}
