import type { SupportSite, SupportTemplate } from "./types";

export const supportTemplates: SupportTemplate[] = [
  { id: "aura-fintech", name: "Apple-style Product Support", category: "Technology", description: "A clean, product-first support home with device choices, popular topics, and personalized help.", priceCents: 1500000, featured: true, enabled: true, theme: { primary: "#0071e3", secondary: "#5ac8fa", background: "#ffffff", surface: "#f5f5f7", text: "#1d1d1f", muted: "#6e6e73", dark: false } },
  { id: "orbit-crypto-saas", name: "Binance-style Crypto Support", category: "Fintech", description: "A dark exchange support center with popular topics, FAQs, and grouped account guides.", priceCents: 1000000, enabled: true, theme: { primary: "#f0b90b", secondary: "#f8d33a", background: "#0b0e11", surface: "#181a20", text: "#eaecef", muted: "#848e9c", dark: true } },
  { id: "cartwise", name: "Bitcoin.com-style Help Center", category: "Fintech", description: "A friendly category-led knowledge base for wallets, buying crypto, Web3, and security.", priceCents: 500000, enabled: true, theme: { primary: "#f7931a", secondary: "#4caf50", background: "#ffffff", surface: "#f5f7fa", text: "#17202a", muted: "#667085", dark: false } },
  { id: "routecare", name: "BYD-style Corporate Contact", category: "Corporate", description: "A polished corporate contact page organized by global region, service, and office.", priceCents: 1000000, enabled: true, theme: { primary: "#e60012", secondary: "#111827", background: "#ffffff", surface: "#f5f5f5", text: "#111111", muted: "#68707a", dark: false } },
  { id: "clarity-docs", name: "Bitso-style Minimal Help", category: "Fintech", description: "A focused support landing page built around search, chat, and promoted articles.", priceCents: 0, featured: true, enabled: true, theme: { primary: "#5b35d5", secondary: "#8b5cf6", background: "#ffffff", surface: "#f7f7fb", text: "#241b35", muted: "#77718a", dark: false } },
  { id: "summit-corporate", name: "Changelly-style Knowledge Base", category: "Fintech", description: "A dense, navigable help center with product areas, article groups, and ticket escalation.", priceCents: 2500000, enabled: true, theme: { primary: "#f05a28", secondary: "#7c3aed", background: "#ffffff", surface: "#fafafa", text: "#202124", muted: "#6b7280", dark: false } },
  { id: "plainhelp", name: "Cash App-style Topic Directory", category: "Fintech", description: "A friendly, spacious support hub with popular questions, topic browsing, and chat support.", priceCents: 0, enabled: true, theme: { primary: "#00d64f", secondary: "#111111", background: "#ffffff", surface: "#f5f5f5", text: "#111111", muted: "#687076", dark: false } },
  { id: "nightshift", name: "Blockchain.com-style Support Center", category: "Dark Mode", description: "A trusted crypto support center with product cards, featured articles, FAQs, and request support.", priceCents: 1500000, featured: true, enabled: true, theme: { primary: "#1652f0", secondary: "#4c8bf5", background: "#f7f9fc", surface: "#ffffff", text: "#172033", muted: "#667085", dark: false } },
];

const variantContent: Record<string, { businessName: string; heroTitle: string; heroSubtitle: string; categories: string[]; articles: string[]; faqs: string[] }> = {
  "aura-fintech": { businessName: "EazyTool Support", heroTitle: "How can we help you?", heroSubtitle: "Get support for your tools, account, and EazyTool services.", categories: ["Receipt Generator", "AI Automation", "Websites", "Image Tools", "Account", "Billing"], articles: ["Forgot your account password?", "How to create a receipt", "Manage your subscription", "Find your saved projects", "Contact the support team"], faqs: ["How do I reset my password?", "Where can I manage my subscription?", "How do I contact EazyTool support?"] },
  "orbit-crypto-saas": { businessName: "EazyTool", heroTitle: "How can we help you?", heroSubtitle: "Find answers to common questions, learn about EazyTool features, and get support for your account.", categories: ["Account Security", "Using EazyTool", "Subscriptions", "Verification", "Troubleshooting", "API & Integrations"], articles: ["How do I secure my EazyTool account?", "What should I do if I cannot access my account?", "How do I change my subscription?", "How do I contact customer support?"], faqs: ["How do I secure my EazyTool account?", "What should I do if I cannot access my account?", "How do I manage my plan?"] },
  "cartwise": { businessName: "EazyTool Help", heroTitle: "Advice and answers from the EazyTool team", heroSubtitle: "Browse guides for getting started, subscriptions, tools, and account safety.", categories: ["Getting Started", "Using EazyTool", "Subscriptions", "Account Security", "Troubleshooting", "Other"], articles: ["Creating your EazyTool account", "How to use the Receipt Generator", "Managing your subscription", "Keeping your account secure", "Common troubleshooting steps"], faqs: ["How do I get started?", "Which tools are included in my plan?", "How can I contact the team?"] },
  "routecare": { businessName: "EazyTool Global", heroTitle: "Contact us", heroSubtitle: "Find the right EazyTool team for your region and support need.", categories: ["Global Headquarters", "Americas", "Europe", "Asia Pacific", "Middle East & Africa", "Customer Service"], articles: ["Global support contacts", "Customer service hours", "Technical support", "Partnership enquiries", "Billing enquiries"], faqs: ["What are your customer service hours?", "How do I reach technical support?", "Where can I send a partnership request?"] },
  "clarity-docs": { businessName: "EazyTool", heroTitle: "How can we help?", heroSubtitle: "Search our help center or open a chat with an expert.", categories: ["Getting Started", "Account", "Subscriptions", "Tools", "Troubleshooting", "Contact Support"], articles: ["How to use EazyTool", "How to upgrade your plan", "How to access a tool", "How to recover your account"], faqs: ["How do I open a chat?", "How do I upgrade my subscription?", "How do I access my tools?"] },
  "summit-corporate": { businessName: "EazyTool Knowledge Base", heroTitle: "How can we help you today?", heroSubtitle: "Search the knowledge base or browse a product area below.", categories: ["Getting Started", "My Account", "Tools & Features", "Subscriptions", "Troubleshooting", "Contact Support"], articles: ["What is EazyTool?", "How to create and manage your account", "How to use your included tools", "Managing subscription billing", "How to submit a support ticket"], faqs: ["What is EazyTool?", "How do I manage my subscription?", "Where can I submit a ticket?"] },
  "plainhelp": { businessName: "EazyTool Support", heroTitle: "How can we help?", heroSubtitle: "Personalized help is one step away.", categories: ["Account", "Payments", "Tools", "Security", "Troubleshooting", "Contact"], articles: ["Protecting your account", "How do I access an old account?", "Where is my subscription?", "How do I cancel a payment?", "Keeping your EazyTool account secure"], faqs: ["How do I start a chat?", "How do I keep my account secure?", "How do I cancel my subscription?"] },
  "nightshift": { businessName: "EazyTool Support Center", heroTitle: "How can we help?", heroSubtitle: "EazyTool Support Center for tools, subscriptions, and account assistance.", categories: ["EazyTool Account", "Receipt Generator", "AI Automation", "Subscriptions", "Security", "Technical Support"], articles: ["I cannot access my account", "How to use the Receipt Generator", "How to manage subscription billing", "How do I verify my account?", "Forgot your password?"], faqs: ["How do I open an EazyTool account?", "What is the difference between plans?", "How do I recover access to my account?"] },
};

export const defaultArticles = [
  { id: "getting-started", category: "Getting Started", title: "Creating an account", slug: "creating-an-account", description: "Set up your account and begin.", content: "Follow the signup steps and verify your email address." },
  { id: "billing-methods", category: "Billing", title: "Payment methods", slug: "payment-methods", description: "Supported ways to pay.", content: "Review the payment options available for your account." },
  { id: "secure-account", category: "Security", title: "Securing your account", slug: "securing-your-account", description: "Practical account safety guidance.", content: "Use a unique password and enable security features offered by your account provider." },
  { id: "login-help", category: "Troubleshooting", title: "Login problems", slug: "login-problems", description: "Resolve common sign-in issues.", content: "Check your email address, connection, and browser before contacting support." },
];

export function createSupportSite(templateId: string, userId: string, templates = supportTemplates): SupportSite {
  const template = templates.find((item) => item.id === templateId) ?? templates[0] ?? supportTemplates[0];
  const content = variantContent[template.id] ?? variantContent["aura-fintech"];
  const now = new Date().toISOString();
  const id = `site_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const articles = content.articles.map((title, index) => ({ id: `article-${index + 1}`, category: content.categories[index % content.categories.length], title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), description: "Read the guide for clear steps and helpful answers.", content: `# ${title}\n\nFollow the EazyTool support guide for step-by-step help.` }));
  const faqs = content.faqs.map((question, index) => ({ id: `faq-${index + 1}`, question, answer: "Choose an enabled support option below and our team will help you resolve this quickly.", category: content.categories[index % content.categories.length] }));
  return { id, userId, name: `${template.name} Project`, slug: `${template.id}-${Math.random().toString(36).slice(2, 6)}`, templateId: template.id, status: "draft", branding: { businessName: content.businessName, logoUrl: "", faviconUrl: "", heroImageUrl: "", primary: template.theme.primary, secondary: template.theme.secondary, background: template.theme.background, text: template.theme.text, font: "Inter", radius: template.id === "plainhelp" ? 8 : 18, buttonStyle: template.id === "plainhelp" ? "square" : "rounded" }, contact: { email: "support@example.com", phone: "+1 555 0142", whatsappUrl: "", telegramUrl: "", liveChatUrl: "", businessHours: "Monday–Friday, 9:00–17:00", enabled: { email: true, phone: false, whatsapp: false, telegram: false, liveChat: true } }, seo: { title: `${content.businessName} | Help Center`, description: content.heroSubtitle, keywords: "support, help center, knowledge base", socialImageUrl: "" }, sections: ["hero", "search", "topics", "categories", "faq", "knowledge", "announcements", "contact", "hours", "social", "footer"].map((section) => ({ id: section as SupportSite["sections"][number]["id"], enabled: !["announcements", "social"].includes(section) })), heroTitle: content.heroTitle, heroSubtitle: content.heroSubtitle, searchPlaceholder: "Search articles, guides and FAQs...", categories: content.categories, articles, faqs, createdAt: now, updatedAt: now };
}

export function formatNaira(cents: number) { return cents === 0 ? "Free" : new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(cents / 100); }
