import type { SupportSite, SupportTemplate } from "./types";

export const supportTemplates: SupportTemplate[] = [
  { id: "aura-fintech", name: "Modern Fintech Support", category: "Fintech", description: "A calm, trustworthy help center for modern financial products.", priceCents: 1500000, featured: true, enabled: true, theme: { primary: "#5b5cf0", secondary: "#7c3aed", background: "#f7f8fc", surface: "#ffffff", text: "#111827", muted: "#667085", dark: false } },
  { id: "orbit-crypto-saas", name: "Crypto SaaS Support", category: "SaaS", description: "An original, security-forward portal for authorized web3 products.", priceCents: 1000000, enabled: true, theme: { primary: "#06b6d4", secondary: "#6366f1", background: "#07111f", surface: "#101d30", text: "#f8fafc", muted: "#94a3b8", dark: true } },
  { id: "cartwise", name: "Ecommerce Help Center", category: "Ecommerce", description: "Friendly support for orders, returns, delivery, and payments.", priceCents: 500000, enabled: true, theme: { primary: "#e84a72", secondary: "#fb923c", background: "#fff8f6", surface: "#ffffff", text: "#241b20", muted: "#78656d", dark: false } },
  { id: "routecare", name: "Logistics Customer Support", category: "Logistics", description: "Shipment-first help with tracking, delivery, and claims topics.", priceCents: 1000000, enabled: true, theme: { primary: "#0f9f78", secondary: "#0ea5e9", background: "#f3faf8", surface: "#ffffff", text: "#10231d", muted: "#667d75", dark: false } },
  { id: "clarity-docs", name: "SaaS Knowledge Base", category: "SaaS", description: "Documentation-led support for onboarding and product education.", priceCents: 0, featured: true, enabled: true, theme: { primary: "#2563eb", secondary: "#8b5cf6", background: "#f7f9fd", surface: "#ffffff", text: "#172033", muted: "#667085", dark: false } },
  { id: "summit-corporate", name: "Corporate Support Center", category: "Corporate", description: "Structured multi-department support for established organizations.", priceCents: 2500000, enabled: true, theme: { primary: "#163f73", secondary: "#2c6eaa", background: "#f4f7fb", surface: "#ffffff", text: "#14243a", muted: "#65758b", dark: false } },
  { id: "plainhelp", name: "Minimal Help Desk", category: "Technology", description: "A focused, distraction-free support experience for any product.", priceCents: 0, enabled: true, theme: { primary: "#111827", secondary: "#475569", background: "#ffffff", surface: "#f8fafc", text: "#111827", muted: "#64748b", dark: false } },
  { id: "nightshift", name: "Dark Technology Support", category: "Dark Mode", description: "A high-contrast technical support hub for developer products.", priceCents: 1500000, featured: true, enabled: true, theme: { primary: "#8b5cf6", secondary: "#22d3ee", background: "#070a12", surface: "#111827", text: "#f8fafc", muted: "#94a3b8", dark: true } },
];

export const defaultArticles = [
  { id: "getting-started", category: "Getting Started", title: "Creating an account", slug: "creating-an-account", description: "Set up your account and begin.", content: "# Creating an account\n\nFollow the signup steps and verify your email address." },
  { id: "billing-methods", category: "Billing", title: "Payment methods", slug: "payment-methods", description: "Supported ways to pay.", content: "# Payment methods\n\nReview the payment options available for your account." },
  { id: "secure-account", category: "Security", title: "Securing your account", slug: "securing-your-account", description: "Practical account safety guidance.", content: "# Securing your account\n\nUse a unique password and enable security features offered by your account provider." },
  { id: "login-help", category: "Troubleshooting", title: "Login problems", slug: "login-problems", description: "Resolve common sign-in issues.", content: "# Login problems\n\nCheck your email address, connection, and browser before contacting support." },
];

export function createSupportSite(templateId: string, userId: string, templates = supportTemplates): SupportSite {
  const template = templates.find((item) => item.id === templateId) ?? templates[0] ?? supportTemplates[0];
  const now = new Date().toISOString();
  const id = `site_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  return { id, userId, name: `${template.name} Project`, slug: `${template.id}-${Math.random().toString(36).slice(2, 6)}`, templateId: template.id, status: "draft", branding: { businessName: "Your Business", logoUrl: "", faviconUrl: "", heroImageUrl: "", primary: template.theme.primary, secondary: template.theme.secondary, background: template.theme.background, text: template.theme.text, font: "Inter", radius: 18, buttonStyle: "rounded" }, contact: { email: "support@example.com", phone: "+1 555 0142", whatsappUrl: "", telegramUrl: "", liveChatUrl: "", businessHours: "Monday–Friday, 9:00–17:00", enabled: { email: true, phone: false, whatsapp: false, telegram: false, liveChat: true } }, seo: { title: `${template.name} | Help Center`, description: "Find answers, guides, and support for our products and services.", keywords: "support, help center, knowledge base", socialImageUrl: "" }, sections: ["hero", "search", "topics", "categories", "faq", "knowledge", "announcements", "contact", "hours", "social", "footer"].map((section) => ({ id: section as SupportSite["sections"][number]["id"], enabled: !["announcements", "social"].includes(section) })), heroTitle: "How can we help you?", heroSubtitle: "Search our guides or browse a topic to find the answer you need.", searchPlaceholder: "Search articles, guides and FAQs...", categories: ["Account", "Getting Started", "Security", "Billing", "Orders", "Troubleshooting"], articles: defaultArticles, faqs: [{ id: "faq-1", question: "How do I contact support?", answer: "Choose any enabled contact method below and our team will help.", category: "General" }, { id: "faq-2", question: "Where can I find product guides?", answer: "Browse the knowledge base or use the search field above.", category: "Getting Started" }], createdAt: now, updatedAt: now };
}

export function formatNaira(cents: number) { return cents === 0 ? "Free" : new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(cents / 100); }
