"use client";
import * as React from "react";
import Link from "next/link";
import { Loader2, Search, ShieldCheck } from "lucide-react";
import { useAuth } from "@/context/auth-context";
import { getAuthHeaders } from "@/lib/licensing/client-auth";
import { domainPriceNaira, COMMON_TLDS, type DomainAvailability } from "@/types/domains";
import { Button } from "@/components/ui/button";
export default function DomainsPage() { const { user } = useAuth(); const [query, setQuery] = React.useState(""); const [results, setResults] = React.useState<DomainAvailability[]>([]); const [loading, setLoading] = React.useState(false); const [message, setMessage] = React.useState(""); async function search(e: React.FormEvent) { e.preventDefault(); if (!user) { setMessage("Please sign in to search for domains."); return; } setLoading(true); setMessage(""); try { const headers = await getAuthHeaders(); const res = await fetch("/api/domains/search", { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ domain: query }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setResults(data.results ?? []); if (!data.configured) setMessage("Live domain availability is not configured yet. Connect ResellerClub to enable production searches."); } catch (e) { setMessage(e instanceof Error ? e.message : "Search failed."); } finally { setLoading(false); } } async function buy(domain: string) { if (!user) return setMessage("Please sign in to buy a domain."); const headers = await getAuthHeaders(); const res = await fetch("/api/domains/checkout/initialize", { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ domain }) }); const data = await res.json(); if (!res.ok) return setMessage(data.error); if (data.authorizationUrl) window.location.href = data.authorizationUrl; else setMessage(data.message ?? "Checkout is ready once Paystack is configured."); }
return <main className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8"><section className="rounded-3xl bg-primary/[0.08] px-6 py-16 text-center sm:px-12"><ShieldCheck className="mx-auto size-8 text-primary" /><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">Find your perfect domain</h1><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Search, register, and manage your online identity from one place.</p><form onSubmit={search} className="mx-auto mt-8 flex max-w-2xl gap-2"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="yourbusiness.com" className="h-12 w-full rounded-xl border bg-background pl-11 pr-4 outline-none" /></div><Button type="submit" disabled={loading}>{loading ? <Loader2 className="size-4 animate-spin" /> : "Search"}</Button></form><div className="mt-5 flex flex-wrap justify-center gap-2 text-xs text-muted-foreground">{COMMON_TLDS.slice(0, 8).map((tld) => <span key={tld} className="rounded-full border px-3 py-1">{tld}</span>)}</div>{message && <p className="mt-5 text-sm text-muted-foreground">{message}</p>}</section><section className="mt-12">{results.length > 0 && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{results.map((item) => <div key={item.domain} className="glass rounded-2xl p-5"><div className="flex items-center justify-between gap-3"><span className="font-semibold">{item.domain}</span><span className={item.available ? "text-emerald-600" : "text-muted-foreground"}>{item.available ? "Available" : "Unavailable"}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-muted-foreground">{domainPriceNaira(item.priceCents)} / year</span><Button size="sm" disabled={!item.available} onClick={() => buy(item.domain)}>Buy Domain</Button></div></div>)}</div>}{!results.length && <div className="py-16 text-center text-muted-foreground">Search for a domain name to see availability and pricing.</div>}</section><p className="mt-10 text-center text-sm text-muted-foreground">Already own a domain? <Link href="/dashboard/domains" className="text-primary hover:underline">Manage your domains</Link></p></main>; }
