"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Copy, ExternalLink, Plus, Trash2 } from "lucide-react";
import { useAuth } from "@/context/auth-context";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { deleteSupportSite, getUserSupportSites, saveSupportSite } from "@/lib/support-sites/store";
import type { SupportSite } from "@/lib/support-sites/types";

export default function SupportWebsitesPage(){const {user,loading}=useAuth();const router=useRouter();const [sites,setSites]=useState<SupportSite[]>([]);useEffect(()=>{if(!loading&&!user)router.replace("/auth/login");if(user)getUserSupportSites(user.uid).then(setSites)},[user,loading,router]);
 const update=async(site:SupportSite)=>{await saveSupportSite(site);setSites(items=>items.map(x=>x.id===site.id?site:x))};
 return <main className="mx-auto max-w-7xl px-4 py-14"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-primary">Creator dashboard</p><h1 className="mt-2 text-3xl font-semibold">My Support Websites</h1><p className="mt-2 text-muted-foreground">Create, manage, and publish your customer help centers.</p></div><Button asChild><Link href="/support-templates"><Plus className="size-4"/>New website</Link></Button></div><div className="mt-8 grid gap-4">{sites.map(site=><article key={site.id} className="glass flex flex-col gap-4 rounded-2xl p-5 md:flex-row md:items-center"><div className="flex-1"><div className="flex gap-2"><h2 className="font-semibold">{site.name}</h2><Badge variant={site.status==="published"?"default":"outline"}>{site.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">/{site.slug} · Updated {new Date(site.updatedAt).toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" asChild><Link href={`/support-templates/${site.templateId}/editor?site=${site.id}`}>Edit</Link></Button><Button size="sm" variant="secondary" asChild><Link href={`/s/${site.slug}`} target="_blank"><ExternalLink className="size-4"/>Preview</Link></Button><Button size="sm" variant="secondary" onClick={()=>{const copy={...site,id:`site_${Date.now()}`,name:`${site.name} Copy`,slug:`${site.slug}-copy`,status:"draft" as const,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};saveSupportSite(copy).then(()=>setSites(x=>[...x,copy]))}}><Copy className="size-4"/>Duplicate</Button><Button size="sm" onClick={()=>update({...site,status:site.status==="published"?"draft":"published"})}>{site.status==="published"?"Unpublish":"Publish"}</Button><Button size="icon" variant="ghost" onClick={()=>deleteSupportSite(site.id).then(()=>setSites(x=>x.filter(y=>y.id!==site.id)))}><Trash2 className="size-4"/></Button></div></article>)}{!sites.length&&!loading&&<div className="rounded-3xl border border-dashed py-20 text-center"><h2 className="text-xl font-semibold">Your first help center starts here.</h2><p className="mt-2 text-muted-foreground">Choose a template, personalize it, and publish.</p><Button className="mt-5" asChild><Link href="/support-templates">Browse templates</Link></Button></div>}</div></main>}
