"use client";

import * as React from "react";
import { Loader2, RefreshCw, ShieldOff, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useRequireAdmin } from "@/hooks/use-require-admin";
import { getAuthHeaders } from "@/lib/licensing/client-auth";
import type { EmailDomainRecord } from "@/lib/email-domains/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type AdminEmailDomain = EmailDomainRecord & { senders: string[]; paymentStatus: string; registrationStatus: string; refundState: string };

export default function AdminEmailDomainsPage() {
  const { isAdmin, loading: authLoading } = useRequireAdmin(); const [domains, setDomains] = React.useState<AdminEmailDomain[]>([]); const [loading, setLoading] = React.useState(true); const [busy, setBusy] = React.useState("");
  const load = React.useCallback(async () => { const headers = await getAuthHeaders(); const response = await fetch("/api/email-domains/admin", { headers, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDomains(data.domains ?? []); }, []);
  React.useEffect(() => { if (!isAdmin) return; load().catch((error) => toast.error(error instanceof Error ? error.message : "Email domains could not be loaded.")).finally(() => setLoading(false)); }, [isAdmin, load]);
  async function action(id: string, actionName: "retry" | "suspend" | "restore") { const reason = actionName === "suspend" ? window.prompt("Why should sending be suspended?") : ""; if (actionName === "suspend" && !reason) return; setBusy(`${id}:${actionName}`); try { const headers = await getAuthHeaders(); const response = await fetch("/api/email-domains/admin", { method: "PATCH", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ id, action: actionName, reason }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); toast.success("Email-domain status updated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(""); } }
  if (authLoading || !isAdmin || loading) return <div className="flex justify-center py-24"><Loader2 className="size-6 animate-spin" /></div>;
  return <main className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><h1 className="text-3xl font-semibold">Email domains</h1><p className="mt-2 text-muted-foreground">Registration, DNS, verification, senders, delivery health, failures, refunds, and sending controls.</p><div className="mt-8 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1320px] text-left text-sm"><thead className="bg-muted/40"><tr>{["Domain / owner", "Payment", "Registration", "Email setup", "Senders", "Sent", "Delivery", "Bounces", "Complaints", "Failure / refund", "Actions"].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{domains.map((domain) => { const delivered = domain.sentCount ? Math.round(domain.deliveredCount / domain.sentCount * 100) : 0; const bounce = domain.sentCount ? (domain.bouncedCount / domain.sentCount * 100).toFixed(1) : "0.0"; return <tr key={domain.id} className="border-t align-top"><td className="px-4 py-4"><div className="font-medium">{domain.domain}</div><div className="mt-1 font-mono text-xs text-muted-foreground">{domain.userId}</div></td><td className="px-4 py-4"><Badge variant="outline">{domain.paymentStatus.replaceAll("_", " ")}</Badge></td><td className="px-4 py-4"><Badge variant="outline">{domain.registrationStatus.replaceAll("_", " ")}</Badge></td><td className="px-4 py-4"><Badge variant={domain.status === "ready" && !domain.suspended ? "default" : "outline"}>{domain.suspended ? "suspended" : domain.status.replaceAll("_", " ")}</Badge></td><td className="px-4 py-4 text-xs">{domain.senders.join(", ") || "—"}</td><td className="px-4 py-4">{domain.sentCount}</td><td className="px-4 py-4">{delivered}%</td><td className="px-4 py-4">{bounce}%</td><td className="px-4 py-4">{domain.complaintCount}</td><td className="max-w-64 px-4 py-4 text-xs text-destructive">{domain.lastError ?? domain.suspensionReason ?? (domain.refundState !== "not_required" ? domain.refundState.replaceAll("_", " ") : "—")}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => action(domain.id, "retry")} disabled={Boolean(busy)}>{busy === `${domain.id}:retry` ? <Loader2 className="size-3 animate-spin" /> : <RefreshCw className="size-3" />}Retry</Button><Button size="sm" variant="outline" onClick={() => action(domain.id, domain.suspended ? "restore" : "suspend")} disabled={Boolean(busy)}>{domain.suspended ? <ShieldCheck className="size-3" /> : <ShieldOff className="size-3" />}{domain.suspended ? "Restore" : "Suspend"}</Button></div></td></tr>; })}</tbody></table>{domains.length === 0 && <p className="py-12 text-center text-sm text-muted-foreground">No email domains have been provisioned.</p>}</div></main>;
}
