"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Loader2, Mail, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { getAuthHeaders } from "@/lib/licensing/client-auth";
import type { EmailDomainRecord } from "@/lib/email-domains/types";
import type { DomainRecord } from "@/types/domains";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const statusLabel = (status?: EmailDomainRecord["status"]) => status === "setting_up" ? "Setting up email" : status === "verifying" ? "Verifying domain" : status === "ready" ? "Email ready" : status === "failed" ? "Setup failed" : "Not started";

export default function DomainManagePage() {
  const params = useParams<{ domain: string }>(); const domainName = decodeURIComponent(params.domain); const [domain, setDomain] = React.useState<DomainRecord | null>(null); const [emailDomain, setEmailDomain] = React.useState<EmailDomainRecord | null>(null); const [busy, setBusy] = React.useState(false);
  const load = React.useCallback(async () => { const headers = await getAuthHeaders(); const [domainResponse, emailResponse] = await Promise.all([fetch(`/api/domains/manage?domain=${encodeURIComponent(domainName)}`, { headers, cache: "no-store" }), fetch("/api/email-domains", { headers, cache: "no-store" })]); const [domainData, emailData] = await Promise.all([domainResponse.json(), emailResponse.json()]); setDomain(domainData.domain ?? null); setEmailDomain((emailData.domains ?? []).find((item: EmailDomainRecord) => item.domainId === domainData.domain?.id) ?? null); }, [domainName]);
  React.useEffect(() => { load().catch(() => toast.error("Domain details could not be loaded.")); }, [load]);
  async function setupEmail() { if (!domain) return; setBusy(true); try { const headers = await getAuthHeaders(); const response = await fetch("/api/email-domains/provision", { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify({ domainId: domain.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); toast.success(data.emailDomain?.status === "ready" ? "Email is ready." : "Email-domain verification started."); } catch (error) { toast.error(error instanceof Error ? error.message : "Email setup failed."); } finally { setBusy(false); } }
  if (!domain) return <div className="flex justify-center py-24"><Loader2 className="size-6 animate-spin" /></div>;
  return <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6"><Link href="/dashboard/domains" className="text-sm text-primary hover:underline">← My Domains</Link><h1 className="mt-5 text-3xl font-semibold">{domain.domain}</h1><div className="mt-8 grid gap-5 md:grid-cols-2"><section className="glass rounded-2xl p-6"><h2 className="text-lg font-semibold">Domain overview</h2><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Registration</dt><dd className="capitalize">{domain.registrationStatus?.replaceAll("_", " ") ?? domain.status}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Registered</dt><dd>{domain.registeredAt ? new Date(domain.registeredAt).toLocaleDateString() : "—"}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Expires</dt><dd>{domain.expiresAt ? new Date(domain.expiresAt).toLocaleDateString() : "—"}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Renewal</dt><dd className="capitalize">{domain.renewalStatus?.replaceAll("_", " ") ?? "Manual"}</dd></div></dl></section><section className="glass rounded-2xl p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Email domain</h2><p className="mt-1 text-sm text-muted-foreground">Automatic SPF, DKIM, DMARC and return-path setup.</p></div><Mail className="size-5 text-primary" /></div><div className="mt-5 flex items-center gap-3"><Badge variant={emailDomain?.status === "ready" ? "default" : "outline"}>{statusLabel(emailDomain?.status)}</Badge>{emailDomain?.status === "ready" && <ShieldCheck className="size-4 text-emerald-500" />}</div>{emailDomain?.lastError && <p className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{emailDomain.lastError}</p>}<Button className="mt-5" variant="secondary" onClick={setupEmail} disabled={busy || emailDomain?.status === "ready"}>{busy && <Loader2 className="size-4 animate-spin" />}{emailDomain?.status === "failed" ? "Retry email setup" : emailDomain?.status ? "Check setup" : "Set up email"}</Button>{emailDomain?.status === "ready" && <Button className="mt-3 ml-2" asChild><Link href="/platform/email-designer">Create sender</Link></Button>}</section></div><section className="mt-5 rounded-2xl border border-dashed p-6"><h2 className="font-semibold">DNS management</h2><p className="mt-2 text-sm text-muted-foreground">EazyTool manages email verification records automatically after the live ResellerClub connection is configured. Manual changes are disabled so the dashboard never reports a DNS update that was not accepted by the registrar.</p></section></main>;
}
