"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ExternalLink, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/context/auth-context";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { createPremiumSite, type PremiumSite } from "@/lib/premium-sites/types";
import { deletePremiumSite, getPremiumSites, savePremiumSite } from "@/lib/premium-sites/client";
import { VolterraSite } from "./volterra-site";

export function PremiumTemplateStudio(){const{user}=useAuth();const[sites,setSites]=useState<PremiumSite[]>([]);const[site,setSite]=useState<PremiumSite|null>(null);const[saving,setSaving]=useState(false);useEffect(()=>{if(user)getPremiumSites().then(setSites).catch(e=>toast.error(e.message))},[user]);
 const create=()=>{if(user)setSite(createPremiumSite(user.uid))};const update=<K extends keyof PremiumSite>(key:K,value:PremiumSite[K])=>setSite(current=>current?{...current,[key]:value}:current);
 const save=async()=>{if(!site)return;setSaving(true);try{const saved=await savePremiumSite(site);setSite(saved);setSites(items=>[saved,...items.filter(item=>item.id!==saved.id)]);toast.success("Premium website saved")}catch(e){toast.error(e instanceof Error?e.message:"Could not save website")}finally{setSaving(false)}};
 if(site)return <div className="min-h-screen bg-muted/30"><header className="sticky top-0 z-40 flex flex-wrap items-center justify-between gap-3 border-b bg-background px-5 py-3"><div><p className="font-semibold">Volterra template admin</p><p className="text-xs text-muted-foreground">Owner-only website settings</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>setSite(null)}>Back</Button>{site.status==="published"&&<Button variant="secondary" asChild><Link target="_blank" href={`/v/${site.slug}`}><ExternalLink className="size-4"/>Open site</Link></Button>}<Button disabled={saving} onClick={save}>{saving?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}{saving?"Saving…":"Save"}</Button></div></header><div className="grid lg:grid-cols-[360px_minmax(0,1fr)]"><aside className="space-y-4 border-r bg-background p-5"><Field label="Project name" value={site.name} onChange={v=>update("name",v)}/><Field label="Public URL slug" value={site.slug} onChange={v=>update("slug",v.toLowerCase().replace(/[^a-z0-9-]/g,"-"))}/><Field label="Brand name" value={site.brandName} onChange={v=>update("brandName",v)}/><Field label="Tagline" value={site.tagline} onChange={v=>update("tagline",v)}/><Field label="Hero title" value={site.heroTitle} onChange={v=>update("heroTitle",v)}/><label className="block"><Label>Hero description</Label><textarea className="mt-1 min-h-24 w-full rounded-xl border bg-background p-3 text-sm" value={site.heroSubtitle} onChange={e=>update("heroSubtitle",e.target.value)}/></label><Field label="Contact number" value={site.contactPhone} onChange={v=>update("contactPhone",v)}/><Field label="Contact email" type="email" value={site.contactEmail} onChange={v=>update("contactEmail",v)}/><Field label="Business address" value={site.address} onChange={v=>update("address",v)}/><Field label="Brand color" type="color" value={site.primaryColor} onChange={v=>update("primaryColor",v)}/><label className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>Published</span><input type="checkbox" checked={site.status==="published"} onChange={e=>update("status",e.target.checked?"published":"draft")}/></label></aside><main className="overflow-auto p-5"><div className="mx-auto max-w-6xl overflow-hidden rounded-2xl border shadow-xl"><VolterraSite site={site}/></div></main></div></div>;
 return <main className="mx-auto max-w-7xl px-4 py-14"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge>Premium template</Badge><h1 className="mt-4 text-4xl font-semibold">Hosted website templates</h1><p className="mt-2 max-w-2xl text-muted-foreground">Create your own editable instance with private owner controls and a public website.</p></div><Button onClick={create}><Plus className="size-4"/>Create Volterra site</Button></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><article className="overflow-hidden rounded-3xl border bg-card"><div className="h-72 overflow-hidden"><div className="pointer-events-none h-[620px] w-[160%] origin-top-left scale-[.48]"><VolterraSite site={createPremiumSite("preview")} compact/></div></div><div className="p-6"><Badge variant="outline">EV & Market Simulation</Badge><h2 className="mt-3 text-2xl font-semibold">Volterra EV Marketplace</h2><p className="mt-2 text-muted-foreground">A bold red-and-black automotive marketplace with illustrative market content and an owner-editable admin area.</p><Button className="mt-5" onClick={create}>Use template</Button></div></article><section><h2 className="text-xl font-semibold">My websites</h2><div className="mt-4 space-y-3">{sites.map(item=><article key={item.id} className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">/v/{item.slug}</p></div><Badge variant={item.status==="published"?"default":"outline"}>{item.status}</Badge></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={()=>setSite(item)}>Open admin</Button>{item.status==="published"&&<Button size="sm" variant="secondary" asChild><Link target="_blank" href={`/v/${item.slug}`}>View site</Link></Button>}<Button size="sm" variant="destructive" onClick={()=>{if(confirm(`Delete ${item.name}?`))deletePremiumSite(item.id).then(()=>setSites(rows=>rows.filter(row=>row.id!==item.id)))}}><Trash2 className="size-4"/>Delete</Button></div></article>)}{!sites.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">No premium websites yet.</div>}</div></section></div></main>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1"/></div>}
