import { ArrowRight, BarChart3, BatteryCharging, Globe2, Mail, MapPin, Phone, ShieldCheck, Zap } from "lucide-react";
import type { PremiumSite } from "@/lib/premium-sites/types";

const markets = [["EVX", "$184.20", "+2.8%"], ["SOLR", "$92.14", "+1.4%"], ["GRID", "$48.08", "+3.1%"], ["LITH", "$71.55", "−0.6%"]];
const vehicles = [["Astra S", "Long-range electric sedan", "610 km"], ["Nova X", "Intelligent electric crossover", "540 km"], ["Pulse GT", "Performance grand tourer", "495 km"]];

export function VolterraSite({ site, compact = false }: { site: PremiumSite; compact?: boolean }) {
  return <div className="min-h-full bg-[#08090b] text-white" style={{ "--volterra": site.primaryColor } as React.CSSProperties}>
    <header className="flex items-center justify-between border-b border-white/10 px-6 py-5 lg:px-12"><div className="flex items-center gap-3 text-lg font-black uppercase tracking-[.22em]"><span className="grid size-9 place-items-center rounded-full bg-[var(--volterra)]"><Zap className="size-5"/></span>{site.brandName}</div><nav className="hidden gap-7 text-sm text-white/65 md:flex"><span>Markets</span><span>EV Marketplace</span><span>About</span><span>Contact</span></nav><a href={`tel:${site.contactPhone}`} className="rounded-full border border-white/15 px-4 py-2 text-sm">{site.contactPhone}</a></header>
    <main><section className={`${compact?"px-6 py-14":"px-6 py-24 lg:px-12 lg:py-32"} relative overflow-hidden`}><div className="absolute -right-32 -top-32 size-[34rem] rounded-full bg-[var(--volterra)]/20 blur-3xl"/><div className="relative mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.28em] text-[var(--volterra)]">{site.tagline}</p><h1 className={`${compact?"mt-4 text-4xl":"mt-6 max-w-4xl text-6xl md:text-8xl"} font-black uppercase leading-[.92] tracking-[-.06em]`}>{site.heroTitle}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/60">{site.heroSubtitle}</p><div className="mt-9 flex flex-wrap gap-3"><button className="rounded-full bg-[var(--volterra)] px-6 py-3 font-semibold">Explore the platform</button><button className="rounded-full border border-white/15 px-6 py-3 font-semibold">Browse electric <ArrowRight className="ml-2 inline size-4"/></button></div></div></section>
      <section className="border-y border-white/10 bg-white/[.03] px-6 py-6 lg:px-12"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 md:grid-cols-4">{markets.map(([symbol,price,move])=><div key={symbol}><p className="text-xs text-white/45">{symbol} · simulated</p><p className="mt-1 text-xl font-semibold">{price}</p><p className={move.startsWith("+")?"text-sm text-emerald-400":"text-sm text-rose-400"}>{move}</p></div>)}</div></section>
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-12"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[var(--volterra)]">Drive the change</p><h2 className="mt-3 text-4xl font-bold">Electric, reimagined.</h2></div><BatteryCharging className="size-10 text-[var(--volterra)]"/></div><div className="mt-10 grid gap-5 md:grid-cols-3">{vehicles.map(([name,copy,range],index)=><article key={name} className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><div className="grid aspect-[1.7] place-items-center rounded-2xl bg-gradient-to-br from-white/10 to-transparent"><span className="text-7xl font-black text-white/[.06]">0{index+1}</span></div><h3 className="mt-6 text-2xl font-semibold">{name}</h3><p className="mt-2 text-white/50">{copy}</p><p className="mt-6 text-sm"><Zap className="mr-2 inline size-4 text-[var(--volterra)]"/>{range} estimated range</p></article>)}</div></section>
      {!compact&&<section className="bg-white px-6 py-20 text-black lg:px-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div><BarChart3 className="size-7 text-[var(--volterra)]"/><h3 className="mt-4 text-xl font-bold">Market simulator</h3><p className="mt-2 text-black/60">Explore illustrative quotes and learn how market tools work without real funds.</p></div><div><ShieldCheck className="size-7 text-[var(--volterra)]"/><h3 className="mt-4 text-xl font-bold">Transparent by design</h3><p className="mt-2 text-black/60">Every financial value and vehicle listing is clearly marked as simulated.</p></div><div><Globe2 className="size-7 text-[var(--volterra)]"/><h3 className="mt-4 text-xl font-bold">Built for your brand</h3><p className="mt-2 text-black/60">Customize the identity and contact details from your owner admin page.</p></div></div></section>}
    </main>
    <footer className="border-t border-white/10 px-6 py-10 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row"><div><p className="font-bold uppercase tracking-[.18em]">{site.brandName}</p><p className="mt-2 max-w-xl text-sm text-white/45">{site.announcement}</p></div><div className="space-y-2 text-sm text-white/60"><p><Phone className="mr-2 inline size-4"/>{site.contactPhone}</p><p><Mail className="mr-2 inline size-4"/>{site.contactEmail}</p><p><MapPin className="mr-2 inline size-4"/>{site.address}</p></div></div></footer>
  </div>;
}
